version: 2
services:
  schwerelos-berlin:
    git_url: <https://github.com/vanStaen/schwerelos-berlin>
    git_branch: master
    ports:
    - container: 5000
      http: 80
    dockerfile_path: Dockerfile